name: "AutoIndex PDFs in README"
description: "Automatically update README.md with links to PDFs in the repository."
inputs:
  github_token:
    description: "The GitHub token to use for deployment."
    required: true
  year:
    description: "The year the PDFs are for."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run Script
      shell: bash
      run: autoindex.sh
      env:
        YEAR: ${{ inputs.year }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./
        force_orphan: true
