name: "AutoIndex PDFs in README"
description: "Automatically update README.md with links to PDFs in the repository."
inputs:
  year:
    description: "The year to use in the README."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run Script
      shell: bash
      run: autoindex.sh
      env:
        YEAR: ${{ inputs.year }}
