name: "AutoIndex PDFs in README"
description: "Automatically update README.md with links to PDFs in the repository."
inputs:
  github_token:
    description: "The GitHub token to use for deployment."
    required: true
  year:
    description: "The year the PDFs are for."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Copy PDFs to GitHub Path
      run: cp -r ./*.pdf $GITHUB_ACTION_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Copy README to GitHub Path
      run: cp -r ./readme.md $GITHUB_ACTION_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: corepack enable
      shell: bash

    - name: Install GraphicsMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y graphicsmagick
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - run: yarn install
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: yarn build
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        ELEVENTY_ENV: production
        GITHUB_WORKSPACE: ${{ github.workspace }}
        YEAR: ${{ inputs.year }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ${{ github.action_path }}/_site
        force_orphan: true
